import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
       <link rel="icon" href="/portfolio.png" sizes="any" />
        <link rel="shortcut icon" href="/portfolio.png" />
        <link rel="apple-touch-icon" href="/portfolio.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
